---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: mjraadi/terraform-cicd-workflows/.github/workflows/terraform-module-release.yml@main
    name: GitHub Release
